Add problem check event.
Stanford-Online/xblock-submit-and-compare pull request #15
Opened 2017-01-04 23:10 UTC by dcadams

@kluo @caseylitton please review.

FYI: @jbassen

2017-01-04 23:25 UTC, caseylitton commented on submit_and_compare/submit_and_compare.py
> +
extra space at end of file

2017-01-04 23:26 UTC, caseylitton commented
look good +1

2017-01-05 01:18 UTC, kluo requested changes

2017-01-05 01:18 UTC, kluo commented on submit_and_compare/submit_and_compare.py
> +                'max_grade': self.weight,
per f2f discussion, max_grade sould be 1.0

2017-01-05 20:50 UTC, merged