Make XBlock due_date and graceperiod aware
Stanford-Online/xblock-submit-and-compare pull request #21
Opened 2018-07-11 22:02 UTC by saharm1

- Adds mixin to check subsection duedate and course graceperiod
- Pushes version to 0.5.3
- Different from free-response in that it hides the buttons, whereas free-response prevents them from ever being created. 

@caesar2164 @stvstnfrd

2018-07-11 22:11 UTC, caesar2164 requested changes
Good first pass!

We need to figure out if the behavior this gives us is ok though.

2018-07-11 22:11 UTC, caesar2164 commented on submit_and_compare/submit_and_compare.py
> +        if self.max_attempts > 0 and self.count_attempts >= self.max_attempts or self.is_past_due():
This should probably be a sub-function like in the free-text xblock.

2018-07-11 22:11 UTC, caesar2164 commented on submit_and_compare/submit_and_compare.py
> +                not_past_due=not self.is_past_due(),
I don't think this gets used in the HTML, remove.

2018-07-11 22:11 UTC, caesar2164 commented on submit_and_compare/submit_and_compare.py
> +            'is_past_due': self.is_past_due(),
This isn't needed, remove.

2018-07-11 22:11 UTC, caesar2164 commented on submit_and_compare/submit_and_compare.py
> +            }
now that we're doubling a lot of this code, let's see if we can't coalesce it and make it more elegant.

2018-07-11 22:11 UTC, caesar2164 commented on submit_and_compare/submit_and_compare.py
> +from xblockutils.studio_editable import StudioEditableXBlockMixin
I don't think this import actually gets used/is needed in the current form of this xblock.

2018-07-12 00:12 UTC, stvstnfrd requested changes
A few comments, mostly formatting/whitespace, but looking good.

2018-07-12 00:12 UTC, stvstnfrd commented on setup.py
> +    version='0.5.3',
We usually bump version numbers in a separate commit.
I can show you (and @tkim135) how to split this out via `edit` inside an interactive rebase.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/mixins.py
> +    xBlock Mixin to allow xblocks to check the due date
Nit: `Allow XBlocks to....`

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> -
Undo this.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +		prompt=prompt,
Per f2f, revert change and use soft spaces instead of hard tabs.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +	}
Revert.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +	if self.max_attempts > 0 and self.count_attempts >= self.max_attempts:
Spaces not tabs.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +	    'success':success,
Add a space after the `:`.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +	    'problem_progress': self._get_problem_progress(),
Fix tabs vs spaces, here and throughout.

2018-07-12 00:12 UTC, stvstnfrd commented on submit_and_compare/submit_and_compare.py
> +	    LOG.error(
Decide whether or not we need logging here and if so,
which level of verbosity is appropriate [1].

[1] https://docs.python.org/2/library/logging.html

2018-07-19 21:45 UTC, saharm1 commented
outdated - should i delete this PR?

2018-07-19 21:46 UTC, caesar2164 commented
yep, you can close it.

2018-07-19 21:46 UTC, closed without merging